# Water Linked DVL A50 Configuration Parameters

# Network settings
dvl_host: "192.168.2.95" # Default IP address for DVL
dvl_port: 16171 # TCP port for JSON protocol

# Frame settings
frame_id: "dvl_link" # DVL sensor frame
odom_frame_id: "odom" # Odometry frame
publish_tf: true # Whether to publish TF transforms

# Connection settings
connection_timeout: 5.0 # Socket connection timeout (seconds)
reconnect_interval: 2.0 # Reconnection attempt interval (seconds)

# Topic remapping (if needed)
topics:
  odometry: "dvl/odometry"
  pose: "dvl/pose"
  altitude: "dvl/altitude"

# Services
services:
  acoustic_control: "dvl/set_acoustic_enabled"
