services:
  barracuda-dvl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: barracuda-dvl
    container_name: barracuda-dvl
    user: root
    privileged: true
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  barracuda-dvl-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-dvl-dev
    container_name: barracuda-dvl-dev
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../barracuda_dvl:/ros2_ws/src/barracuda_dvl
    profiles: ["dev"]
